# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d91fb3533b7f6d2aae8fcffd443c2632a44fb5cb943301320a5e5ca541a8a6133ec8fc578708eb837389fe648df87d7a83a36894682e4666ec5585b4d40c4d4

test:
  secret_key_base: a88699b62707b4264c1a3a204cb8940e68afa108d1a9442bee21f239a831610ff9037ccc9b91ef3574c50b2119e7a78f7589fcfaa46df2c39c5d0d38c4696114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
